version: 2
updates:
- package-ecosystem: cargo
  directory: "/workspace/debugger_core"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/workspace/ptrace"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/workspace/debugger_ui"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/workspace"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
